package token;

/**
 * a class that represents a JSON String literal
 * inherits from the AbstractToken class
 */
public class TokenString extends AbstractToken {

  /**
   * Constructor for TokenString
   * 
   * @param literal The string value generated by the lexer
   */
  public TokenString(String literal) {
    super(TokenType.STRING, literal);
  }

  /**
   * Class specific implementation of the evaluate method signature.
   * allows us to return a proper Java object based on the value and tokentype
   * of the class.
   *
   * * @return The string value
   */
  @Override
  public Object evaluate() {
    // since the value is already a string from the lexer, we just return the
    // litteral
    return getLiteral();
  }
}
